[package]
name = "rust-national-park"
version = "0.1.0"
authors = ["Jack Pantalena <12242683+jpantalena@users.noreply.github.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
